name: Build
on:
  workflow_call:
    outputs:
      artifact-name:
        description: Name of artifact to upload
        value: awesome-blog-client
      build-version:
        description: build date
        value: ${{ jobs.build-version.outputs.build-version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: awesome-blog-client
          path: dist

  build-version:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.BuildVersion.outputs.build-version }}
    steps:
      - id: BuildVersion
        name: BuildVersion
        run: echo "build-version=v$(date +"%Y%m%d%H%M")" >> $GITHUB_OUTPUT
