name: Trigger on push main
on:
  push:
    branches:
      - main

env:
  aws-deployment-role-arn: 'arn:aws:iam::781550338764:role/awesome-city-cicd'
  aws-s3-artifact-bucket: ${{ secrets.AWS_S3_BUCKET_CMN_MODULE }}

jobs:
  test:
    uses: ./.github/workflows/_test.yaml

  codeQL:
    uses: ./.github/workflows/_codeql.yaml

  build:
    needs:
      - test
    uses: ./.github/workflows/_build.yaml
    with:
      aws-role-arn: ${{ env.aws-deployment-role-arn }}
      aws-s3-artifact-bucket: ${{ env.aws-s3-artifact-bucket }}

  tag:
    needs:
      - build
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.Tag.outputs.build-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OWNER_PAT }}

      - id: Tag
        name: Push Tag
        run: |
          echo ${{ needs.build.outputs.build-version}}
          git tag ${{ needs.build.outputs.build-version}}
          git push origin ${{ needs.build.outputs.build-version}}
          echo "build-version=${{ needs.build.outputs.build-version}}" >> $GITHUB_OUTPUT
