name: Trigger test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    uses: ./.github/workflows/_test.yaml

  codeQL:
    uses: ./.github/workflows/_codeql.yaml

  build:
    uses: ./.github/workflows/_build.yaml
    with:
      dry-run: true
    secrets: inherit
