name: Trigger test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  codeQL:
    uses: ./.github/workflows/codeql.yaml
