name: Build
on:
  push:
    branches:
      - master
      - release
      - develop

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  build:
    uses: ./.github/workflows/build.yaml

  upload-module:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: awesome-blog-client
          path: ./awesome-blog-client

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload
        run: |
          aws s3 cp \
          ./awesome-blog-client/ \
          s3://awesome-cmn-mdl/artifact/blog/client/${{ needs.build.outputs.build-version}}/ \
          --recursive

  tag:
    needs:
      - upload-module
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push Tag
        run: |
          git tag ${{ needs.build.outputs.build-version}}
          git push origin ${{ needs.build.outputs.build-version}}
